name = "hexdocs_offline"
version = "1.0.1"

description = "Downloads an offline version of the hexdocs of your projects dependencies to a local folder"
licences = ["Apache-2.0"]

repository = { type = "github", user = "daniellionel01", repo = "hexdocs_offline" }

internal_modules = [
  "hexdocs_offline/internal",
  "hexdocs_offline/internal/*",
  "hexdocs_offline/dev",
  "hexdocs_offline/dev/*",
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
tom = ">= 1.1.0 and < 2.0.0"
glexec = ">= 1.0.3 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
nakai = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
